stages:
  data_ingestion:
    cmd: python src/spellX/pipeline/stage_01_data_ingestion.py
    deps:
      - src/spellX/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data

  data_validation:
    cmd: python src/spellX/pipeline/stage_02_data_validation.py
    deps:
      - src/spellX/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  model_trainig:
    cmd: python src/spellX/pipeline/stage_03_model_training.py
    deps:
      - src/spellX/pipeline/stage_03_model_training.py
      - config/config.yaml
    outs:
      - artifacts/model_trainer/model0.pkl
  
  model_evaluation:
    cmd: python src/spellX/pipeline/stage_04_model_evaluation.py
    deps:
      - src/spellX/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
    outs:
      - artifacts/model_evaluation/metrics.txt